import React, { useState, useEffect } from 'react';
import Sidebar from '../components/Sidebar';
import { useStore } from '../store/useStore';
import { apiClient } from '../api/client';
import {
  Activity, Sparkles, Lock, ShieldCheck,
  CheckCircle2, Radio, Info, Loader2, StopCircle, Headphones, Music
} from 'lucide-react';
import toast from 'react-hot-toast';
import PageTransition from '../components/PageTransition';
import { motion, AnimatePresence } from 'framer-motion';

// Animated audio equalizer to simulate active listening/monitoring
const EqualizerSim = ({ active }) => {
  return (
    <div className="flex items-end gap-1 h-8">
      {[1, 2, 3, 4, 5].map((i) => (
        <motion.div
          key={i}
          className="w-2 rounded-t-sm"
          style={{ backgroundColor: active ? '#FFB347' : '#ffffff20' }}
          animate={active ? {
            height: ["20%", "80%", "40%", "100%", "30%"],
          } : { height: "20%" }}
          transition={{
            duration: 1.2,
            repeat: Infinity,
            ease: 'easeInOut',
            delay: i * 0.1,
          }}
        />
      ))}
    </div>
  );
};

const permissions = [
  { icon: Music, label: 'Media Activity Telemetry', desc: 'Metadata on currently playing tracks, podcasts, and duration. Actual audio files are NEVER recorded or stored.', granted: true },
  { icon: Headphones, label: 'Listening Habits', desc: 'Monitors the genre shifts, acoustic valence, and energy of the media you consume locally.', granted: true },
  { icon: ShieldCheck, label: 'On-Device Processing', desc: 'All pattern analysis runs locally. Only anonymized mood correlations leave your device.', granted: true },
];

const MusicMood = () => {
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [monitoringActive, setMonitoringActive] = useState(true);
  const [lastAnalysed, setLastAnalysed] = useState(null);
  const { updateRiskData } = useStore();

  // Simulate passive auto-analysis on mount (representing background monitoring)
  useEffect(() => {
    const timer = setTimeout(() => {
      setLastAnalysed(new Date());
    }, 1500);
    return () => clearTimeout(timer);
  }, []);

  // Auto-trigger analysis
  const handleAutoAnalyze = async () => {
    setLoading(true);
    try {
      // Simulate real behavioral payload that media session telemetry would provide
      // Using behavior/log endpoint as a proxy to update risk score in db
      const payload = {
        social_time_mins: 120, // Reused field to represent listening duration
        screen_time_mins: 0,
        messages_sent: 0,
        messages_replied: 0,
        mood_context: "Autogenerated from high-energy electronic music and true crime podcasts indicating alert or potential high-stress periods."
      };
      
      const res = await apiClient.post('/api/user/behavior/log', payload);
      setResult({
        ...res.data,
        analysis: {
          acoustic_valence: "45% (Neutral)",
          high_energy_tracks: "68%",
          genre_shift: "Pop -> Electronic",
          listening_duration: "120m"
        }
      });
      setLastAnalysed(new Date());
      updateRiskData();
      toast.success('Passive media analysis complete');
    } catch (err) {
      toast.error('Media telemetry logging failed');
    } finally {
      setLoading(false);
    }
  };

  return (
    <PageTransition>
      <div className="flex bg-bg min-h-screen w-full">
        <Sidebar />
        <main className="flex-1 ml-64 p-8 max-w-5xl">

          {/* Header */}
          <header className="mb-8">
            <div className="flex items-center gap-3 mb-2">
              <div className="p-3 bg-[#FFB347]/20 rounded-xl">
                <Headphones className="text-[#FFB347] w-6 h-6" />
              </div>
              <h1 className="text-3xl font-bold">Music Mood Analysis</h1>
            </div>
            <p className="text-text-secondary max-w-2xl">
              AmbientMind securely monitors your playing audio—including songs, podcasts, and audiobooks—to analyze genre shifts, listening duration, and mood correlations passively.
            </p>
          </header>

          {/* Live Monitoring Status Card */}
          <motion.div
            initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}
            className="glass rounded-3xl p-6 mb-6 border border-[#FFB347]/20 relative overflow-hidden"
          >
            <div className="absolute top-0 right-0 w-48 h-48 bg-[#FFB347]/5 rounded-full blur-[80px] pointer-events-none" />
            <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
              <div className="flex items-center gap-4">
                <div className="relative">
                  <div className={`w-14 h-14 rounded-2xl flex items-center justify-center ${monitoringActive ? 'bg-[#FFB347]/20' : 'bg-white/5'} transition-colors`}>
                    {monitoringActive ? <Radio className="w-7 h-7 text-[#FFB347]" /> : <StopCircle className="w-7 h-7 text-text-secondary" />}
                  </div>
                  {monitoringActive && (
                    <span className="absolute -top-1 -right-1 w-3 h-3 rounded-full bg-safe border-2 border-bg animate-ping" />
                  )}
                  {monitoringActive && (
                    <span className="absolute -top-1 -right-1 w-3 h-3 rounded-full bg-safe border-2 border-bg" />
                  )}
                </div>
                <div>
                  <div className="flex items-center gap-2">
                    <h2 className="font-bold text-lg">{monitoringActive ? 'Passive Monitoring Active' : 'Monitoring Paused'}</h2>
                    {monitoringActive && <span className="px-2 py-0.5 text-xs font-bold bg-safe/20 text-safe rounded-full">LIVE</span>}
                  </div>
                  <p className="text-text-secondary text-sm mt-0.5">
                    {monitoringActive
                      ? 'AmbientMind is securely reading media session metadata.'
                      : 'Enable monitoring to resume audio pattern analysis.'}
                  </p>
                  {lastAnalysed && (
                    <p className="text-xs text-[#FFB347] mt-1 font-medium">
                      Last passive sync: {lastAnalysed.toLocaleTimeString()}
                    </p>
                  )}
                </div>
              </div>

              <div className="flex items-center gap-6">
                <EqualizerSim active={monitoringActive} />
                <button
                  onClick={() => setMonitoringActive(v => !v)}
                  className={`px-4 py-2 rounded-xl text-sm font-bold transition-all ${
                    monitoringActive
                      ? 'bg-white/10 text-white hover:bg-white/15'
                      : 'bg-[#FFB347]/20 text-[#FFB347] hover:bg-[#FFB347]/30'
                  }`}
                >
                  {monitoringActive ? 'Pause' : 'Resume'}
                </button>
              </div>
            </div>
          </motion.div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">

            {/* How It Works */}
            <motion.div
              initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }}
              className="glass rounded-3xl p-7"
            >
              <div className="flex items-center gap-2 mb-6">
                <Info className="w-5 h-5 text-[#FFB347]" />
                <h2 className="text-lg font-bold">How Music Mood Works</h2>
              </div>
              <div className="space-y-5">
                {[
                  { step: '01', title: 'Media Session Tracking', desc: 'Reads the metadata of your currently playing tracks and podcasts via the OS media controller.' },
                  { step: '02', title: 'Valence & Energy', desc: 'Cross-references genres to establish acoustic valence (positivity) and energy levels.' },
                  { step: '03', title: 'Emotional Correlation', desc: 'Sudden shifts to sad acoustic music or extended true crime podcasts can flag mood drops locally.' },
                ].map((item, i) => (
                  <div key={i} className="flex gap-4">
                    <div className="shrink-0 w-8 h-8 rounded-lg bg-[#FFB347]/20 text-[#FFB347] text-xs font-black flex items-center justify-center">{item.step}</div>
                    <div>
                      <p className="font-semibold text-sm mb-0.5">{item.title}</p>
                      <p className="text-text-secondary text-xs leading-relaxed">{item.desc}</p>
                    </div>
                  </div>
                ))}
              </div>

              {/* Request manual trigger */}
              <div className="mt-7 pt-6 border-t border-white/5">
                <p className="text-xs text-text-secondary mb-3">Force sync current device telemetry to dashboard?</p>
                <motion.button
                  whileHover={{ scale: 1.02 }} whileTap={{ scale: 0.98 }}
                  onClick={handleAutoAnalyze}
                  disabled={loading || !monitoringActive}
                  className="w-full py-3 bg-[#FFB347]/20 hover:bg-[#FFB347]/30 text-[#FFB347] rounded-xl font-bold text-sm flex items-center justify-center gap-2 disabled:opacity-50 transition-colors mb-6 border border-[#FFB347]/30"
                >
                  {loading
                    ? <><Loader2 className="w-4 h-4 animate-spin" /> Syncing data...</>
                    : <><Activity className="w-4 h-4" /> Sync Audio Telemetry</>
                  }
                </motion.button>
              </div>

              {/* Manual Override Section */}
              <div className="mt-8 pt-6 border-t border-white/5">
                <div className="flex items-center gap-2 mb-4">
                  <Activity className="w-5 h-5 text-alert" />
                  <h3 className="font-bold text-alert">Manual Clinical Entry</h3>
                </div>
                <p className="text-xs text-text-secondary mb-4">For clinical surveillance or manual data entry operations.</p>
                <form className="space-y-4" onSubmit={(e) => { e.preventDefault(); handleAutoAnalyze(); }}>
                  <div>
                    <div className="flex justify-between text-xs font-semibold mb-1 text-text-secondary">
                      <span>Daily Listening Time (mins)</span>
                    </div>
                    <input type="range" className="w-full h-2 bg-white/20 rounded-lg appearance-none cursor-pointer" min="0" max="600" defaultValue="120" />
                  </div>
                  <div>
                    <div className="flex justify-between text-xs font-semibold mb-1 text-text-secondary">
                      <span>Acoustic Valence (0-100)</span>
                    </div>
                    <input type="range" className="w-full h-2 bg-white/20 rounded-lg appearance-none cursor-pointer" min="0" max="100" defaultValue="45" />
                  </div>
                  <div>
                    <div className="flex justify-between text-xs font-semibold mb-1 text-text-secondary">
                      <span>High-Energy Tracks %</span>
                    </div>
                    <input type="range" className="w-full h-2 bg-white/20 rounded-lg appearance-none cursor-pointer" min="0" max="100" defaultValue="68" />
                  </div>
                  <button type="submit" className="w-full py-2 bg-white/5 hover:bg-white/10 border border-white/10 text-white rounded-lg text-sm font-semibold transition-colors mt-4">
                    Submit Manual Data
                  </button>
                </form>
              </div>
            </motion.div>

            {/* Right column — Results + Permissions */}
            <div className="space-y-6">

              {/* Analysis Result */}
              <AnimatePresence>
                {result ? (
                  <motion.div
                    key="result"
                    initial={{ opacity: 0, scale: 0.95 }}
                    animate={{ opacity: 1, scale: 1 }}
                    exit={{ opacity: 0 }}
                    className="glass p-7 rounded-3xl border border-[#FFB347]/30"
                  >
                    <div className="flex items-center justify-between mb-5">
                      <h3 className="font-bold text-lg">Latest Snapshot</h3>
                      <div className="px-3 py-1 bg-white/10 rounded-full text-xs font-semibold">
                        Media Logged
                      </div>
                    </div>

                    <div className="bg-[#FFB347]/10 border border-[#FFB347]/20 rounded-xl p-5 mb-5">
                      <div className="flex items-center gap-2 mb-2 font-semibold text-sm">
                        <Sparkles className="w-4 h-4 text-[#FFB347]" /> Proxy Insight
                      </div>
                      <p className="text-sm leading-relaxed text-white/80">
                        {result.message || 'Telemetry indicates high-energy electronic music and true crime podcasts typical of alert or potential high-stress periods.'}
                      </p>
                    </div>

                    <div className="space-y-3 text-sm">
                      {[
                        { label: 'Acoustic Valence', value: result.analysis?.acoustic_valence },
                        { label: 'High Energy Tracks', value: result.analysis?.high_energy_tracks },
                        { label: 'Dominant Shift', value: result.analysis?.genre_shift },
                        { label: 'Listening Duration', value: result.analysis?.listening_duration },
                      ].map(({ label, value }, i) => (
                        <div key={i} className="flex justify-between items-center border-b border-white/5 pb-2">
                          <span className="text-text-secondary">{label}</span>
                          <span className="font-bold">{value}</span>
                        </div>
                      ))}
                    </div>
                  </motion.div>
                ) : (
                  <motion.div
                    key="placeholder"
                    initial={{ opacity: 0 }} animate={{ opacity: 1 }}
                    className="glass p-7 rounded-3xl border border-white/5 flex flex-col items-center justify-center text-center min-h-[200px]"
                  >
                    <div className="w-14 h-14 bg-[#FFB347]/10 rounded-full flex items-center justify-center mb-4">
                      <Headphones className="w-7 h-7 text-[#FFB347]/60" />
                    </div>
                    <h3 className="font-medium mb-1">Passively tracking sessions...</h3>
                    <p className="text-sm text-text-secondary max-w-xs">
                      AmbientMind requires at least 1 hour of audio playback to determine genre shifts and mood correlations.
                    </p>
                  </motion.div>
                )}
              </AnimatePresence>

              {/* Permissions */}
              <motion.div
                initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.3 }}
                className="glass rounded-3xl p-6"
              >
                <div className="flex items-center gap-2 mb-5">
                  <Lock className="w-4 h-4 text-[#FFB347]" />
                  <h3 className="font-bold">Active Permissions</h3>
                </div>
                <div className="space-y-4">
                  {permissions.map((p, i) => (
                    <div key={i} className="flex items-start gap-3">
                      <div className="w-8 h-8 rounded-lg bg-white/5 flex items-center justify-center shrink-0 mt-0.5">
                        <p.icon className="w-4 h-4 text-[#FFB347]" />
                      </div>
                      <div className="flex-1">
                        <div className="flex items-center gap-2 mb-0.5">
                          <span className="text-sm font-semibold">{p.label}</span>
                          {p.granted && <CheckCircle2 className="w-3.5 h-3.5 text-safe" />}
                        </div>
                        <p className="text-xs text-text-secondary leading-relaxed">{p.desc}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </motion.div>
            </div>
          </div>
        </main>
      </div>
    </PageTransition>
  );
};

export default MusicMood;
