import React, { useState, useEffect } from 'react';
import Sidebar from '../components/Sidebar';
import { useStore } from '../store/useStore';
import { apiClient } from '../api/client';
import {
  Keyboard, Activity, Sparkles, Lock, MessageSquareText, ShieldCheck,
  CheckCircle2, Radio, Info, Loader2, StopCircle
} from 'lucide-react';
import toast from 'react-hot-toast';
import PageTransition from '../components/PageTransition';
import { motion, AnimatePresence } from 'framer-motion';

// Animated typing indicator using a simulated typing pattern
const TypingSim = ({ active }) => {
  return (
    <div className="flex items-center gap-1.5 h-6">
      {[0, 1, 2].map((i) => (
        <motion.div
          key={i}
          className="w-2.5 h-2.5 rounded-full"
          style={{ backgroundColor: active ? '#6C63FF' : '#ffffff20' }}
          animate={active ? {
            y: ["0%", "-50%", "0%"],
            opacity: [0.4, 1, 0.4]
          } : { y: "0%", opacity: 0.2 }}
          transition={{
            duration: 0.8,
            repeat: Infinity,
            ease: 'easeInOut',
            delay: i * 0.15,
          }}
        />
      ))}
    </div>
  );
};

const permissions = [
  { icon: Keyboard, label: 'Keyboard Telemetry', desc: 'Metadata on typing speed, backspaces, and pauses. Keystroke content is NEVER read or stored.', granted: true },
  { icon: MessageSquareText, label: 'Communication Frequency', desc: 'Monitors the volume and rhythm of outgoing vs incoming messages locally.', granted: true },
  { icon: ShieldCheck, label: 'On-Device Processing', desc: 'All pattern analysis runs locally. Only anonymized behavioral metrics leave your device.', granted: true },
];

const TypingAssessment = () => {
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [monitoringActive, setMonitoringActive] = useState(true);
  const [lastAnalysed, setLastAnalysed] = useState(null);
  const { updateRiskData } = useStore();

  // Simulate passive auto-analysis on mount (representing background monitoring)
  useEffect(() => {
    const timer = setTimeout(() => {
      setLastAnalysed(new Date());
    }, 1500);
    return () => clearTimeout(timer);
  }, []);

  // Auto-trigger analysis
  const handleAutoAnalyze = async () => {
    setLoading(true);
    try {
      // Simulate real behavioral payload that the OS keyboard telemetry would provide
      const payload = {
        social_time_mins: 145,
        screen_time_mins: 320,
        messages_sent: 24,
        messages_replied: 18,
        mood_context: "Autogenerated from high variance typing speeds and increased backspace usage indicating potential anxiety."
      };
      
      const res = await apiClient.post('/api/user/behavior/log', payload);
      setResult({
        ...res.data,
        analysis: {
          wpm_variance: "+12%",
          backspace_rate: "High",
          sentiment_proxy: "Anxious",
          response_latency: "2.4m"
        }
      });
      setLastAnalysed(new Date());
      updateRiskData();
      toast.success('Passive behavioral analysis complete');
    } catch (err) {
      toast.error('Typing telemetry logging failed');
    } finally {
      setLoading(false);
    }
  };

  return (
    <PageTransition>
      <div className="flex bg-bg min-h-screen w-full">
        <Sidebar />
        <main className="flex-1 ml-64 p-8 max-w-5xl">

          {/* Header */}
          <header className="mb-8">
            <div className="flex items-center gap-3 mb-2">
              <div className="p-2 bg-secondary/20 rounded-xl">
                <MessageSquareText className="text-secondary w-6 h-6" />
              </div>
              <h1 className="text-3xl font-bold">Chat Analysis</h1>
            </div>
            <p className="text-text-secondary max-w-2xl">
              AmbientMind passively analyses your texting rhythm, frequency, and communication patterns without reading your private messages.
            </p>
          </header>

          {/* Live Monitoring Status Card */}
          <motion.div
            initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}
            className="glass rounded-3xl p-6 mb-6 border border-secondary/20 relative overflow-hidden"
          >
            <div className="absolute top-0 right-0 w-48 h-48 bg-secondary/5 rounded-full blur-[80px] pointer-events-none" />
            <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
              <div className="flex items-center gap-4">
                <div className="relative">
                  <div className={`w-14 h-14 rounded-2xl flex items-center justify-center ${monitoringActive ? 'bg-secondary/20' : 'bg-white/5'} transition-colors`}>
                    {monitoringActive ? <Radio className="w-7 h-7 text-secondary" /> : <StopCircle className="w-7 h-7 text-text-secondary" />}
                  </div>
                  {monitoringActive && (
                    <span className="absolute -top-1 -right-1 w-3 h-3 rounded-full bg-safe border-2 border-bg animate-ping" />
                  )}
                  {monitoringActive && (
                    <span className="absolute -top-1 -right-1 w-3 h-3 rounded-full bg-safe border-2 border-bg" />
                  )}
                </div>
                <div>
                  <div className="flex items-center gap-2">
                    <h2 className="font-bold text-lg">{monitoringActive ? 'Passive Monitoring Active' : 'Monitoring Paused'}</h2>
                    {monitoringActive && <span className="px-2 py-0.5 text-xs font-bold bg-safe/20 text-safe rounded-full">LIVE</span>}
                  </div>
                  <p className="text-text-secondary text-sm mt-0.5">
                    {monitoringActive
                      ? 'AmbientMind is securely reading keyboard telemetry and notification timestamps.'
                      : 'Enable monitoring to resume behavioral pattern analysis.'}
                  </p>
                  {lastAnalysed && (
                    <p className="text-xs text-secondary mt-1 font-medium">
                      Last passive sync: {lastAnalysed.toLocaleTimeString()}
                    </p>
                  )}
                </div>
              </div>

              <div className="flex items-center gap-6">
                <TypingSim active={monitoringActive} />
                <button
                  onClick={() => setMonitoringActive(v => !v)}
                  className={`px-4 py-2 rounded-xl text-sm font-bold transition-all ${
                    monitoringActive
                      ? 'bg-white/10 text-white hover:bg-white/15'
                      : 'bg-secondary/20 text-secondary hover:bg-secondary/30'
                  }`}
                >
                  {monitoringActive ? 'Pause' : 'Resume'}
                </button>
              </div>
            </div>
          </motion.div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">

            {/* How It Works */}
            <motion.div
              initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }}
              className="glass rounded-3xl p-7"
            >
              <div className="flex items-center gap-2 mb-6">
                <Info className="w-5 h-5 text-secondary" />
                <h2 className="text-lg font-bold">How Chat Analysis Works</h2>
              </div>
              <div className="space-y-5">
                {[
                  { step: '01', title: 'Local Telemetry Tracking', desc: 'Securely tracks the speed of your typing, frequency of backspaces, and pauses across communications. Content is never read.' },
                  { step: '02', title: 'Engagement Frequency', desc: 'Measures how often you respond to messages and your average response latency to track social withdrawal.' },
                  { step: '03', title: 'Behavioral Biomarkers', desc: 'Identifies psychomotor agitation or retardation locally. The final aggregated metrics flow into your clinical algorithm.' },
                ].map((item, i) => (
                  <div key={i} className="flex gap-4">
                    <div className="shrink-0 w-8 h-8 rounded-lg bg-secondary/20 text-secondary text-xs font-black flex items-center justify-center">{item.step}</div>
                    <div>
                      <p className="font-semibold text-sm mb-0.5">{item.title}</p>
                      <p className="text-text-secondary text-xs leading-relaxed">{item.desc}</p>
                    </div>
                  </div>
                ))}
              </div>

              {/* Request manual trigger */}
              <div className="mt-7 pt-6 border-t border-white/5">
                <p className="text-xs text-text-secondary mb-3">Force sync current device telemetry to dashboard?</p>
                <motion.button
                  whileHover={{ scale: 1.02 }} whileTap={{ scale: 0.98 }}
                  onClick={handleAutoAnalyze}
                  disabled={loading || !monitoringActive}
                  className="w-full py-3 bg-gradient-to-r from-secondary to-primary text-white rounded-xl font-bold text-sm flex items-center justify-center gap-2 disabled:opacity-50 glow mb-6"
                >
                  {loading
                    ? <><Loader2 className="w-4 h-4 animate-spin" /> Syncing data...</>
                    : <><Activity className="w-4 h-4" /> Sync Hardware Telemetry</>
                  }
                </motion.button>
              </div>

              {/* Manual Override Section */}
              <div className="mt-8 pt-6 border-t border-white/5">
                <div className="flex items-center gap-2 mb-4">
                  <Activity className="w-5 h-5 text-alert" />
                  <h3 className="font-bold text-alert">Manual Clinical Entry</h3>
                </div>
                <p className="text-xs text-text-secondary mb-4">For clinical surveillance or manual data sync operations.</p>
                <form className="space-y-4" onSubmit={(e) => { e.preventDefault(); handleAutoAnalyze(); }}>
                  <div>
                    <label className="block text-xs font-semibold mb-1 text-text-secondary">Social App Usage (mins)</label>
                    <input type="range" className="w-full h-2 bg-white/20 rounded-lg appearance-none cursor-pointer" min="0" max="600" defaultValue="145" />
                  </div>
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <label className="block text-xs font-semibold mb-1 text-text-secondary">Messages Sent</label>
                      <input type="number" className="w-full bg-black/40 border border-white/10 rounded-lg px-3 py-2 text-sm" defaultValue="24" />
                    </div>
                    <div>
                      <label className="block text-xs font-semibold mb-1 text-text-secondary">Replied To</label>
                      <input type="number" className="w-full bg-black/40 border border-white/10 rounded-lg px-3 py-2 text-sm" defaultValue="18" />
                    </div>
                  </div>
                  <button type="submit" className="w-full py-2 bg-white/5 hover:bg-white/10 border border-white/10 text-white rounded-lg text-sm font-semibold transition-colors mt-2">
                    Submit Manual Data
                  </button>
                </form>
              </div>
            </motion.div>

            {/* Right column — Results + Permissions */}
            <div className="space-y-6">

              {/* Analysis Result */}
              <AnimatePresence>
                {result ? (
                  <motion.div
                    key="result"
                    initial={{ opacity: 0, scale: 0.95 }}
                    animate={{ opacity: 1, scale: 1 }}
                    exit={{ opacity: 0 }}
                    className="glass p-7 rounded-3xl border border-secondary/30"
                  >
                    <div className="flex items-center justify-between mb-5">
                      <h3 className="font-bold text-lg">Latest Snapshot</h3>
                      <div className="px-3 py-1 bg-white/10 rounded-full text-xs font-semibold">
                        Behavior Logged
                      </div>
                    </div>

                    <div className="bg-secondary/10 border border-secondary/20 rounded-xl p-5 mb-5">
                      <div className="flex items-center gap-2 mb-2 font-semibold text-sm">
                        <Sparkles className="w-4 h-4 text-secondary" /> Proxy Insight
                      </div>
                      <p className="text-sm leading-relaxed text-white/80">
                        {result.message || 'Telemetry indicates elevated psychomotor agitation typical of high stress or anxiety periods.'}
                      </p>
                    </div>

                    <div className="space-y-3 text-sm">
                      {[
                        { label: 'WPM Variance', value: result.analysis?.wpm_variance },
                        { label: 'Correction Rate', value: result.analysis?.backspace_rate },
                        { label: 'Avg Response Latency', value: result.analysis?.response_latency },
                        { label: 'Communication Volume', value: `${result.behavior_log?.messages_sent || 0} sent` },
                      ].map(({ label, value }, i) => (
                        <div key={i} className="flex justify-between items-center border-b border-white/5 pb-2">
                          <span className="text-text-secondary">{label}</span>
                          <span className="font-bold">{value}</span>
                        </div>
                      ))}
                    </div>
                  </motion.div>
                ) : (
                  <motion.div
                    key="placeholder"
                    initial={{ opacity: 0 }} animate={{ opacity: 1 }}
                    className="glass p-7 rounded-3xl border border-white/5 flex flex-col items-center justify-center text-center min-h-[200px]"
                  >
                    <div className="w-14 h-14 bg-secondary/10 rounded-full flex items-center justify-center mb-4">
                      <Keyboard className="w-7 h-7 text-secondary/60" />
                    </div>
                    <h3 className="font-medium mb-1">Passively aggregating...</h3>
                    <p className="text-sm text-text-secondary max-w-xs">
                      AmbientMind requires at least 4 hours of device interaction for a high-confidence behavioral report.
                    </p>
                  </motion.div>
                )}
              </AnimatePresence>

              {/* Permissions */}
              <motion.div
                initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.3 }}
                className="glass rounded-3xl p-6"
              >
                <div className="flex items-center gap-2 mb-5">
                  <Lock className="w-4 h-4 text-secondary" />
                  <h3 className="font-bold">Active Permissions</h3>
                </div>
                <div className="space-y-4">
                  {permissions.map((p, i) => (
                    <div key={i} className="flex items-start gap-3">
                      <div className="w-8 h-8 rounded-lg bg-white/5 flex items-center justify-center shrink-0 mt-0.5">
                        <p.icon className="w-4 h-4 text-secondary" />
                      </div>
                      <div className="flex-1">
                        <div className="flex items-center gap-2 mb-0.5">
                          <span className="text-sm font-semibold">{p.label}</span>
                          {p.granted && <CheckCircle2 className="w-3.5 h-3.5 text-safe" />}
                        </div>
                        <p className="text-xs text-text-secondary leading-relaxed">{p.desc}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </motion.div>
            </div>
          </div>
        </main>
      </div>
    </PageTransition>
  );
};

export default TypingAssessment;
